# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_cf_C <- function(data, shock, parameters, tolerance, zeta, maxiter, nthreads) {
    .Call(`_LogLT_calc_cf_C`, data, shock, parameters, tolerance, zeta, maxiter, nthreads)
}

calc_cf_mat_C <- function(data, shock, parameters, tolerance, zeta, maxiter, nthreads) {
    .Call(`_LogLT_calc_cf_mat_C`, data, shock, parameters, tolerance, zeta, maxiter, nthreads)
}

